name: studyu_repo_generator
description: A web server to generate/update Gitlab repos
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  dotenv: ^3.0.0
  path: ^1.8.0
  pretty_json: ^2.0.0
  shelf: ^1.1.4
  studyu_core:
    path: ../core
  supabase: ^0.0.1-dev.17

dev_dependencies:
    shelf_hotreload: ^0.0.2
