name: studyu_repo_generator
description: A web server to generate/update Gitlab repos
version: 1.4.8
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.1.1
  dotenv: ^3.0.0
  http: ^0.13.3
  path: ^1.8.1
  pretty_json: ^2.0.0
  shelf: ^1.2.0
  studyu_core:
  supabase: ^0.2.10

dev_dependencies:
    shelf_hotreload: ^1.0.0

executables:
  repo_generator:
