name: generator
description: A web server to generate/update Gitlab repos and Jupyter HTML Notebooks
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dotenv: ^3.0.0-nullsafety.0
  http: ^0.13.1
  path: ^1.8.0
  pretty_json: ^2.0.0
  shelf: ^1.1.0
  studyou_core:
    path: ../core
  supabase: ^0.0.1-dev.13

dev_dependencies:
  lint: ^1.5.3
  shelf_hotreload: ^0.0.2
