include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

# All lints: https://dart-lang.github.io/linter/lints/
linter:
  rules:
    # STYLE
    prefer_single_quotes: true
    cascade_invocations: true # May has issues: https://github.com/dart-lang/linter/issues/1589
    prefer_foreach: true
    prefer_int_literals: true
    use_raw_strings: true

    # FLUTTER WEB IMPORTANT
    avoid_double_and_int_checks: true

    # DISABLE
    # We have prints for better debugging. Maybe not the best option.
    avoid_print: false
    # Highlights localization imports and others which are annoying to fix
    depend_on_referenced_packages: false
