version: '3'
services:
  app:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: app
        ENV: selfhost
    ports:
      - 8081:80
    env_file:
      - flutter_common/lib/envs/.env.selfhost

  designer:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer
        ENV: selfhost
    ports:
      - 8080:80
    env_file:
      - flutter_common/lib/envs/.env.selfhost