version: '3'
services:
  app:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: app
    ports:
      - 8081:80
    env_file:
      - flutter_common/lib/envs/.env
  designer:
    build:
      context: .
      args:
        FLUTTER_APP_FOLDER: designer
    ports:
      - 8080:80
    env_file:
      - flutter_common/lib/envs/.env
