name: studyu-packages

packages:
  - 'app/*'
  - 'common/*'
  - 'core/*'
  - 'generator/*'
  - 'notebook_uploader/*'
  - 'study_designer/*'

scripts:
  tuneup: melos exec -- pub global run tuneup check

  analyze:
    run: |
      melos exec -c 6 -- \
        "flutter analyze --fatal-infos ."
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      melos exec -c 6 -- \
        "dart format -l 120 ."
    description: Format all code

  format:ci:
    run: |
      melos exec -c 6 -- \
        "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' ! -path './proto/*' | tr '\n' ' ' | xargs dart format -l 120 --set-exit-if-changed"
    description: Format all code without generated files

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists: test

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk"
    description: Build app for Android.
    select-package:
      dir-exists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ios --no-codesign"
    description: Build app for iOS.
    select-package:
      dir-exists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web"
    description: Build app for Web.
    select-package:
      dir-exists: web

# Clean things very deeply, can be used to establish "pristine checkout" status
clean:deep: >
  git clean -x -d -f -q

# Additional cleanup lifecycle script, executed when `melos clean` is ran.
postclean: >
  melos exec -c 6 -- "flutter clean"

dev_dependencies:
  lint: ^1.5.3