name: studyu-packages

packages:
  - 'app/*'
  - 'designer/*'
  - 'core/*'
  - 'flutter_common/*'
  - 'repo_generator/*'
  - 'notebook_uploader/*'

scripts:
  tuneup: melos exec -- pub global run tuneup check

  analyze:
    run: |
      melos exec -c 6 -- \
        "flutter analyze --fatal-infos ."
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      melos exec -c 6 -- \
        "dart format -l 120 ."
    description: Format all code

  format:ci:
    run: |
      melos exec -c 6 -- \
        "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' ! -path './proto/*' | tr '\n' ' ' | xargs dart format -l 120 --set-exit-if-changed"
    description: Format all code without generated files

  outdated:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter pub outdated"
    description: Check all outdated dependencies

  upgrade:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter pub upgrade"
    description: Check all outdated dependencies

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists: test

  generate:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate files with build_runner
    select-package:
      scope: studyu_core

  build:android:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build apk --no-tree-shake-icons"
    description: Build app for Android.
    select-package:
      dir-exists: android

  build:ios:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build ipa --no-codesign --no-tree-shake-icons"
    description: Build app for iOS.
    select-package:
      dir-exists: ios

  build:web:
    run: |
      melos exec -c 2 --fail-fast -- \
        "flutter build web --pwa-strategy none --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    select-package:
      dir-exists: web

  build:web:app:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --pwa-strategy none --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    select-package:
      scope: studyu_app

  build:web:designer:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter build web --pwa-strategy none --web-renderer auto --no-tree-shake-icons"
    description: Build app for Web.
    select-package:
      scope: studyu_designer

# Clean things very deeply, can be used to establish "pristine checkout" status
clean:deep: >
  git clean -x -d -f -q

# Additional cleanup lifecycle script, executed when `melos clean` is ran.
postclean: >
  melos exec -c 6 -- "flutter clean"

dev_dependencies:
  lint: ^1.5.3
