name: studyou_core
description: StudYou Models and common functions for app and study designer
version: 3.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: 0.4.6
  flutter_dotenv: ^4.0.0-nullsafety.0
  json_annotation: ^4.0.1
  postgrest: ^0.0.8
  quiver: ^3.0.1
  shared_preferences: ^2.0.5
  supabase: ^0.0.1-dev.11
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  lint: ^1.5.3
