name: studyu_core
description: StudYou Models and common functions for app and study designer
version: 3.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: 0.4.7
  json_annotation: ^4.0.1
  postgrest: ^0.1.2
  quiver: ^3.0.1
  supabase: ^0.0.1-dev.17
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  lint: ^1.5.3
  test: 1.17.5
