name: studyou_core
description: StudYou Models and common functions for app and study designer
version: 2.0.0

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fhir: 0.4.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  json_annotation: ^4.0.1
  parse_server_sdk_flutter:
    path: ../../Parse-SDK-Flutter/packages/flutter
  quiver: ^3.0.0
  uuid: ^3.0.2

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  lint: ^1.5.3

dependency_overrides:
  parse_server_sdk:
    path: ../../Parse-SDK-Flutter/packages/dart
  #uuid: ^3.0.1

