name: studyu_core
description: StudyU Models and common functions for app and designer
version: 3.1.0
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: ^0.4.7
  json_annotation: ^4.0.1
  postgrest: ^0.1.3
  quiver: ^3.0.1
  supabase: ^0.0.1-dev.22
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: 1.17.8
