name: studyu_core
description: StudyU Models and common functions for app and designer
version: 3.7.6
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  csv: ^5.0.1
  fhir: ^0.4.7
  json_annotation: ^4.4.0
  quiver: ^3.0.1
  supabase: ^0.2.14
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lint: 1.8.2
  test: ^1.20.1
