name: studyou_core
description: StudYou Models and common functions for app and study designer
version: 2.0.0

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_dotenv: 3.1.0
  json_annotation: ^3.1.1
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  quiver: ^2.1.5
  uuid: ^2.2.2

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  lint: ^1.5.2
