name: studyu
description: An app to facilitate N-of-1 trials

publish_to: 'none'

version: '1.4.1'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_common: ^0.10.0
  charts_flutter: ^0.10.0
  chewie: ^1.0.0
  cupertino_icons: ^1.0.2
  ext_storage: ^1.0.3
  extended_math:
    git:
      url: https://github.com/nstrelow/extended_math.git
  flutter:
    sdk: flutter
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^1.0.10
  grizzly_distuv: ^1.0.0
  intersperse: ^1.1.1
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  path_provider: ^2.0.1
  pdf: ^3.0.1
  pimp_my_button: ^1.0.0
  provider: ^5.0.0
  quiver: ^3.0.0
  rainbow_color: ^2.0.1
  shared_preferences: ^2.0.4
  studyou_core:
    path: ../core
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.2
  video_player: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

dependency_overrides:
  intl: 0.17.0
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.0.0
  shared_preferences: ^2.0.4
  uuid: ^3.0.1

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true


flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - envs/
