name: studyu
description: An app to facilitate N-of-1 trials

publish_to: 'none'

version: '1.4.1'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter:
    git:
      url: https://github.com/hpi-studyu/charts.git
      ref: git_export
      path: charts_flutter
  chewie: ^0.12.2
  cupertino_icons: ^1.0.1
  ext_storage: ^1.0.3
  extended_math: ^0.0.29+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^4.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^1.0.9
  grizzly_distuv: ^1.0.0
  intersperse: ^1.1.1
  intl: 0.17.0
  material_design_icons_flutter: ^4.0.5855
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  path_provider: ^1.6.27
  pdf: ^2.1.0
  pimp_my_button: ^1.0.0
  provider: ^4.3.3
  quiver: ^2.1.5
  rainbow_color: ^0.1.1
  shared_preferences: ^0.5.12
  studyou_core:
    path: ../core
  timeline_tile: ^1.0.0
  url_launcher: ^5.7.10
  video_player: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

dependency_overrides:
  intl: 0.17.0

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true


flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - envs/
