name: studyu_app
description: An app to facilitate N-of-1 trials
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: '1.10.2'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_common: ^0.11.0
  charts_flutter: ^0.11.0
  chewie: ^1.2.2
  cupertino_icons: ^1.0.3
  extended_math:
    git:
      url: https://github.com/nstrelow/extended_math.git
  flutter:
    sdk: flutter
  flutter_file_dialog: ^2.1.0
  flutter_local_notifications: 7.0.0-dev.2
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  grizzly_distuv: ^1.0.0
  intersperse: ^2.0.0
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info_plus: ^1.0.4
  pdf: ^3.4.2
  pimp_my_button: ^1.0.0
  postgrest: ^0.1.4
  provider: ^5.0.0
  quiver: ^3.0.1
  rainbow_color: ^2.0.1
  shared_preferences: ^2.0.6
  studyu_core:
  studyu_flutter_common:
  supabase: ^0.0.7
  supabase_flutter: ^0.0.7
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  video_player: ^2.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_local_notifications_platform_interface: 4.0.0

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true


flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/fonts/
