name: notebook_uploader
description: A cli tool to upload html of jupyter notebooks to supabase
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  path: ^1.8.0
  studyu_core:
    path: ../core
  supabase: ^0.0.1-dev.17

dev_dependencies:
    shelf_hotreload: ^0.0.2
