name: studyu_flutter_common
description: StudYou Models and common functions for app and study designer
version: 3.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  shared_preferences: ^2.0.6
  studyu_core:
    path: ../core

dev_dependencies:
  lint: ^1.5.3

flutter:
  generate: true

  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.local
