name: studyu_designer
description: StudyU Study designer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  csv: ^5.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  ext_storage: ^1.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^5.0.0
  flutter_iconpicker: ^3.0.0
  flutter_json_widget: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  path_provider: ^2.0.1
  postgrest: ^0.0.8
  pretty_json: ^2.0.0
  provider: ^5.0.0
  studyou_core:
    path: ../core
  supabase: ^0.0.1-dev.11
  universal_html: ^2.0.8
  url_launcher: ^6.0.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

dependency_overrides:
  gotrue:
    git:
      url: https://github.com/supabase/gotrue-dart.git
  image: ^3.0.2
  vin_decoder: ^0.2.0-nullsafety

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - envs/
