name: studyu_designer
description: StudyU Study designer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  csv: ^5.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  ext_storage: ^1.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^5.0.0-alpha.1
  flutter_iconpicker: ^3.0.0-nullsafety
  flutter_json_widget: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  path_provider: ^2.0.1
  pretty_json: ^1.1.0
  provider: ^5.0.0
  studyou_core:
    path: ../core
  universal_html: ^1.2.4
  url_launcher: ^6.0.2
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

dependency_overrides:
  # change if merged: https://github.com/tiholic/date_range_picker
  date_range_picker:
    git:
      url: https://github.com/tiholic/date_range_picker
  dio: ^4.0.0-beta7
  http: ^0.13.0
  image: ^3.0.1
  intl: 0.17.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.4
  uuid: ^3.0.1
  vin_decoder : ^0.2.0-nullsafety

flutter:
  generate: true
  uses-material-design: true

  assets:
    - envs/
