name: studyu_designer
description: StudyU Study designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: 1.5.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.15.0
  csv: ^5.0.0
  cupertino_icons: ^1.0.3
  email_validator: ^2.0.1
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.5.0
  flutter_file_dialog: ^2.1.1
  flutter_form_builder: ^6.0.1
  flutter_iconpicker: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  pretty_json: ^2.0.0
  provider: ^6.0.0
  studyu_core:
  studyu_flutter_common:
  supabase: ^0.2.4
  supabase_flutter: ^0.2.4
  universal_html: ^2.0.8
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  webviewx: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
