name: studyu_designer
description: StudyU Study designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: 1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.15.0
  csv: ^5.0.0
  cupertino_icons: ^1.0.3
  email_validator: ^2.0.1
  fl_chart: ^0.36.2
  flutter:
    sdk: flutter
  flutter_colorpicker: 0.4.0
  flutter_file_dialog: ^2.1.0
  flutter_form_builder: ^6.0.1
  flutter_iconpicker: ^3.0.1
  flutter_json_widget: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  postgrest: ^0.1.3
  pretty_json: ^2.0.0
  provider: ^5.0.0
  studyu_core:
    path: ../core
  studyu_flutter_common:
    path: ../flutter_common
  supabase: ^0.0.1-dev.20
  universal_html: ^2.0.8
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  webviewx: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
