name: studyu_designer
description: StudyU Study designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: 1.5.7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.15.0
  csv: ^5.0.0
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  fl_chart: ^0.40.6
  flutter:
    sdk: flutter
  flutter_file_dialog: ^2.3.0
  flutter_form_builder: ^7.0.0
  flutter_iconpicker: ^3.0.4
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^7.0.0
  form_builder_validators: ^7.2.0
  http: ^0.13.4
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.6595
  pretty_json: ^2.0.0
  provider: ^6.0.1
  studyu_core:
  studyu_flutter_common:
  supabase: ^0.2.10
  supabase_flutter: ^0.2.9
  universal_html: ^2.0.8
  url_launcher: ^6.0.17
  uuid: ^3.0.4
  webviewx: ^0.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_iconpicker:
    git:
      url: https://github.com/Ahmadre/FlutterIconPicker

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
