name: All packages

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install melos
        run: pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Run Analyze"
        run: melos run analyze

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install melos
        run: pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Run Format"
        run: melos run format:ci

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install melos
        run: pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Run Test"
        run: melos run test --no-select

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Enable web support
        run: flutter config --enable-web
      - name: Install melos
        run: pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Web"
        run: melos run build:web --no-select
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDYU_E37AF }}'
          channelId: live
          projectId: studyu-e37af
      - name: Archive App Production Web Build
        uses: actions/upload-artifact@master
        with:
          name: app-web-build
          path: app/build/web
      - name: Archive Designer Production Web Build
        uses: actions/upload-artifact@master
        with:
          name: designer-web-build
          path: designer/build/web