name: Publish Generator Docker image and deploy to Google Cloud Run
on:
  workflow_dispatch:
  push:
    paths:
      - 'core/**'
      - 'generator/**'
      - '.github/**'
    branches:
      - master
      - dev
  release:
    types: [published]

env:
  RUN_REGION: europe-west1
  SERVICE_NAME: studyu-project-generator

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: notebook_uploader/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/hpi-studyu/notebook-uploader:${{ github.sha }},ghcr.io/hpi-studyu/notebook-uploader:latest
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE_NAME" \
          --region "$RUN_REGION" \
          --image gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.RUN_PROJECT }}