# Created with package:mono_repo v4.0.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
      - dev
      - monorepo-ci
  pull_request:
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
  FOO: BAR

jobs:
  job_001:
    name: "unit_test; PKG: app; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.5
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:app;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:app
            os:ubuntu-latest;pub-cache-hosted;dart:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: beta
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: app_pub_upgrade
        name: "app; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: app
        run: pub upgrade --no-precompile
      - name: app; pub run test
        if: "always() && steps.app_pub_upgrade.conclusion == 'success'"
        working-directory: app
        run: pub run test
  job_002:
    name: "unit_test; PKG: common; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.5
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:common;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:common
            os:ubuntu-latest;pub-cache-hosted;dart:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: beta
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: common_pub_upgrade
        name: "common; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
        run: pub upgrade --no-precompile
      - name: common; pub run test
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
        run: pub run test
  job_003:
    name: "unit_test; PKG: study_designer; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.5
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:study_designer;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:beta;packages:study_designer
            os:ubuntu-latest;pub-cache-hosted;dart:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: beta
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: study_designer_pub_upgrade
        name: "study_designer; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: study_designer
        run: pub upgrade --no-precompile
      - name: study_designer; pub run test
        if: "always() && steps.study_designer_pub_upgrade.conclusion == 'success'"
        working-directory: study_designer
        run: pub run test
