name: Dependabot Pub

on:
#  schedule:
#    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  pub:
    name: Dependabot Pub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update
        uses: nstrelow/dependabot-pub-runner@patch-2
        with:
          path: /app