name: Dependabot Pub

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  pub:
    name: Dependabot Pub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Update
        uses: IchordeDionysos/dependabot-pub-runner@main
        with:
          path: /app