name: Upgrade dependencies

on:
#  schedule:
#    - cron: 0 3 * * *
  workflow_dispatch:
jobs:
  test:
    name: Flutter package updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: run flutter package updater
        uses: tianhaoz95/update-flutter-packages@v0.0.5
        with:
          flutter-project: './app'
          git-email: 'strelow.nils@gmail.com'
          git-name: 'Nils Strelow'
          token: ${{ secrets.NILS_GITHUB_TOKEN }}
          target-branch: dev