name: Deploy to Google Cloud Run
on:
  workflow_dispatch:
  push:
    paths:
      - 'core/**'
      - 'generator/**'
      - '.github/workflows/build-docker-generator.yml'
    branches:
      - master
      - dev
  release:
    types: [published]

env:
  RUN_REGION: europe-west1
  SERVICE_NAME: studyu-project-generator

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.RUN_PROJECT }}/${{ env.SERVICE_NAME }}:latest -f generator/Dockerfile .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE_NAME" \
          --region "$RUN_REGION" \
          --image gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.RUN_PROJECT }}
