name: studyu_flutter_common
description: StudYou common flutter components and functions for app and designer
version: 1.2.3
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  shared_preferences: ^2.0.6
  studyu_core:
  uuid: ^3.0.4

flutter:
  generate: true

  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.local
